#!/bin/bash
# 生成 harness.toml 配置文件
# 使用方法：bash scripts/util/generate-harness-toml.sh [项目目录]

set -e

# 颜色定义
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

PROJECT_DIR="${1:-.}"
CONFIG_FILE="$PROJECT_DIR/harness.toml"

echo -e "${BLUE}🔧 开始生成 harness.toml 配置文件...${NC}"
echo -e "${BLUE}📍 目标目录：${PROJECT_DIR}${NC}"

# 检查目录是否存在
if [ ! -d "$PROJECT_DIR" ]; then
    echo -e "${YELLOW}⚠️  目录不存在，将创建：${PROJECT_DIR}${NC}"
    mkdir -p "$PROJECT_DIR"
fi

# 检查配置文件是否已存在
if [ -f "$CONFIG_FILE" ]; then
    echo -e "${YELLOW}⚠️  配置文件已存在：${CONFIG_FILE}${NC}"
    read -p "是否覆盖？(y/n): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "取消操作"
        exit 0
    fi
fi

# 检测项目类型
echo -e "${BLUE}🔍 检测项目类型...${NC}"
HAS_FRONTEND=false
HAS_BACKEND=false

# 检测前端
if [ -f "$PROJECT_DIR/package.json" ] || \
   [ -f "$PROJECT_DIR/vue.config.js" ] || \
   [ -f "$PROJECT_DIR/webpack.config.js" ] || \
   [ -f "$PROJECT_DIR/index.html" ]; then
    HAS_FRONTEND=true
    echo -e "${GREEN}✅ 检测到前端项目${NC}"
fi

# 检测后端
if [ -f "$PROJECT_DIR/pom.xml" ] || \
   [ -f "$PROJECT_DIR/build.gradle" ] || \
   [ -f "$PROJECT_DIR/requirements.txt" ] || \
   [ -f "$PROJECT_DIR/go.mod" ]; then
    HAS_BACKEND=true
    echo -e "${GREEN}✅ 检测到后端项目${NC}"
fi

# 确定项目类型
if [ "$HAS_FRONTEND" = true ] && [ "$HAS_BACKEND" = true ]; then
    PROJECT_TYPE="全栈项目"
    FRONTEND_ENABLED="true"
    BACKEND_ENABLED="true"
elif [ "$HAS_FRONTEND" = true ]; then
    PROJECT_TYPE="前端项目"
    FRONTEND_ENABLED="true"
    BACKEND_ENABLED="false"
elif [ "$HAS_BACKEND" = true ]; then
    PROJECT_TYPE="后端项目"
    FRONTEND_ENABLED="false"
    BACKEND_ENABLED="true"
else
    PROJECT_TYPE="未知项目"
    FRONTEND_ENABLED="false"
    BACKEND_ENABLED="true"  # 默认启用后端
    echo -e "${YELLOW}⚠️  未检测到明确项目类型，使用默认配置${NC}"
fi

echo -e "${GREEN}📊 项目类型：${PROJECT_TYPE}${NC}"

# 生成配置文件
echo -e "${BLUE}📝 生成配置文件...${NC}"

cat > "$CONFIG_FILE" << EOF
# Harness Configuration File
# Generated by Java Harness
# Project Type: $PROJECT_TYPE
# Generated at: $(date +%Y-%m-%d\ %H:%M:%S)

[harness]
version = "5.0.0-java"
backend = "auto"
project_root = "."

[e2e_detection]
enabled = true
mode = "strict"
timeout = 120
retry_on_failure = true
max_retries = 3

# 智能跳过配置 🆕
[e2e_detection.smart_skip]
enabled = true
detect_project_type = true
skip_frontend_if_missing = true
skip_backend_if_missing = false
min_confidence_threshold = 0.7
fallback_strategy = "run_backend"

# 自动修复配置
[e2e_detection.auto_fix]
enabled = true
max_iterations = 3
fix_timeout = 60
commit_on_fix = true

[e2e_detection.auto_fix.types]
dependency_update = true
gitignore_add = true
code_fix = false
test_generation = false

# 前端测试配置
[e2e_detection.test_types.frontend]
enabled = $FRONTEND_ENABLED
framework = "playwright"

[e2e_detection.test_types.frontend.playwright]
timeout = 30000
expect_timeout = 5000
headless = true
viewport_width = 1280
viewport_height = 720
browsers = ["chromium", "firefox", "webkit"]
workers = null
retries = 1

[e2e_detection.test_types.frontend.playwright.features]
auto_wait = true
video_recording = "retain-on-failure"
screenshot = "only-on-failure"
trace = "retain-on-failure"

# 后端测试配置
[e2e_detection.test_types.backend]
enabled = $BACKEND_ENABLED
framework = "auto"
test_paths = ["backend/tests/", "src/test/api/", "test/"]

# 集成测试
[e2e_detection.test_types.integration]
enabled = true
test_scenarios = ["user_login", "data_flow", "error_handling"]

# 安全测试
[e2e_detection.test_types.security]
enabled = true
scan_vulnerabilities = true
check_dependencies = true
scan_secrets = true

# 触发器配置
[e2e_detection.triggers]
auto_trigger_on_review_pass = true
require_clean_workspace = true
skip_on_draft_pr = true
skip_on_wip_branch = true

[e2e_detection.triggers.branch_patterns]
include = ["feature/*", "bugfix/*", "hotfix/*"]
exclude = ["draft/*", "wip/*", "experimental/*"]

# 报告配置
[e2e_detection.reporting]
generate_report = true
report_format = "markdown"
include_details = true
save_artifacts = true
artifacts_location = ".claude/artifacts/e2e-detection/"

# 系统集成配置
[e2e_detection.integration.harness_work]
enabled = true
trigger_point = "after_review"
blocking = true

[e2e_detection.integration.harness_review]
enabled = true
send_feedback = true

# 高级配置
[e2e_detection.advanced]
parallel_execution = true
max_parallel_workers = 3
cache_test_results = true
cache_ttl = 3600
cleanup_after_test = true
fail_fast = false
continue_on_failure = true
debug_mode = false
log_level = "info"
EOF

echo -e "${GREEN}✅ 配置文件生成成功！${NC}"
echo -e "${BLUE}📍 文件位置：${CONFIG_FILE}${NC}"
echo ""
echo -e "${GREEN}📋 配置摘要：${NC}"
echo -e "   项目类型：${PROJECT_TYPE}"
echo -e "   前端测试：$([ "$FRONTEND_ENABLED" = true ] && echo "启用" || echo "禁用")"
echo -e "   后端测试：$([ "$BACKEND_ENABLED" = true ] && echo "启用" || echo "禁用")"
echo -e "   智能跳过：启用"
echo ""
echo -e "${BLUE}💡 下一步：${NC}"
echo -e "   1. 检查配置文件：${GREEN}cat $CONFIG_FILE${NC}"
echo -e "   2. 根据需要调整配置"
echo -e "   3. 验证配置：${GREEN}java -cp target/java-harness-cli.jar com.chachamaru.harness.config.HarnessConfigManager validate $CONFIG_FILE${NC}"
echo ""
echo -e "${YELLOW}⚠️  提示：配置文件包含完整的 E2E 检测配置，包括：${NC}"
echo -e "   - Playwright 前端测试（如适用）"
echo -e "   - 后端 API 测试（如适用）"
echo -e "   - 智能跳过逻辑（自动检测项目类型）"
echo -e "   - 自动修复循环"
echo -e "   - 详细的报告和日志配置"
echo ""