# GraalVM Native Image configuration

# Optimization
-OptimizeSize=2
-H:+RemoveSaturatedExchangeFlows

# Memory
-Xmx4G

# Runtime
-Duser.timezone=UTC
-Dfile.encoding=UTF-8

# Logging
-Dlogback.configurationFile=logback-native.xml
