package com.chachamaru.harness.config;

/**
 * Configuration template generator for harness.toml.
 * Provides methods to generate default and custom configuration templates.
 */
public class ConfigTemplate {

    private static final String DEFAULT_TEMPLATE = """
            # Harness Configuration File
            # Generated by Java Harness

            [harness]
            version = "5.0.0-java"
            backend = "codex"  # Options: codex, cursor, auto
            project_root = "."  # Relative path to project root

            [plan]
            enable = true
            auto_save = true
            backup_count = 5

            [work]
            enable = true
            default_effort = "medium"  # Options: low, medium, high, max
            auto_review = true

            [review]
            enable = true
            strict_mode = false
            max_review_rounds = 3

            [release]
            enable = true
            auto_version = true
            changelog_enabled = true

            [sync]
            enable = true
            auto_sync = false
            sync_on_start = false

            [hooks]
            enable = true
            pre_tool_use = true
            post_tool_use = true
            permission_request = true

            [state]
            persist = true
            session_file = ".claude/state/session.jsonl"
            work_file = ".claude/state/work.jsonl"

            [logging]
            level = "INFO"  # Options: TRACE, DEBUG, INFO, WARN, ERROR
            file = ".claude/logs/harness.log"
            """;

    private static final String MINIMAL_TEMPLATE = """
            # Minimal Harness Configuration
            # Generated by Java Harness

            [harness]
            version = "5.0.0-java"
            backend = "codex"
            project_root = "."

            [plan]
            enable = true

            [work]
            enable = true

            [review]
            enable = true

            [release]
            enable = true

            [sync]
            enable = true

            [hooks]
            enable = true

            [state]
            persist = true

            [logging]
            level = "INFO"
            """;

    /**
     * Generate default configuration template.
     *
     * @return Default TOML configuration string
     */
    public static String generateDefault() {
        return DEFAULT_TEMPLATE;
    }

    /**
     * Generate custom configuration template with specified values.
     *
     * @param version Harness version
     * @param backend Backend type (codex, cursor, auto)
     * @param projectRoot Project root path
     * @return Custom TOML configuration string
     */
    public static String generateCustom(String version, String backend, String projectRoot) {
        return DEFAULT_TEMPLATE
                .replace("5.0.0-java", version)
                .replace("backend = \"codex\"", "backend = \"" + backend + "\"")
                .replace("project_root = \".\"", "project_root = \"" + projectRoot + "\"");
    }

    /**
     * Generate minimal configuration template.
     *
     * @return Minimal TOML configuration string
     */
    public static String generateMinimal() {
        return MINIMAL_TEMPLATE;
    }
}
