package com.chachamaru.harness.cli.command;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Parameters;
import picocli.CommandLine.Option;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Plan generation command for creating and managing Plans.md files.
 *
 * <p>This command provides functionality to:
 * <ul>
 *   <li>create - Create a new Plans.md from template</li>
 *   <li>check - Detect drift between plan status and actual git state</li>
 *   <li>update - Update plan completion status</li>
 *   <li>validate - Validate Plans.md format and structure</li>
 * </ul>
 * </p>
 */
@Command(name = "gen",
         mixinStandardHelpOptions = true,
         subcommands = {
             GenCommand.CreateCommand.class,
             GenCommand.CheckCommand.class,
             GenCommand.UpdateCommand.class,
             GenCommand.ValidateCommand.class
         },
         description = "Generate and manage Plans.md files with drift detection")
public class GenCommand implements Runnable {

    @Option(names = {"-v", "--verbose"}, description = "Show verbose output")
    private boolean verbose;

    @Override
    public void run() {
        // Default behavior - show help
        CommandLine.usage(this, System.out);
    }

    /**
     * Create a new Plans.md from template
     */
    @Command(name = "create",
             mixinStandardHelpOptions = true,
             description = "Create a new Plans.md from template")
    public static class CreateCommand implements Runnable {

        @Option(names = {"-o", "--output"},
                 description = "Output file path (default: Plans.md)",
                 defaultValue = "Plans.md")
        private String outputPath;

        @Option(names = {"-t", "--title"},
                 description = "Plan title",
                 defaultValue = "Project Implementation Plan")
        private String title;

        @Option(names = {"-d", "--description"},
                 description = "Plan description",
                 defaultValue = "Implementation plan for project milestones")
        private String description;

        @Option(names = {"--force"},
                 description = "Overwrite existing file")
        private boolean force;

        @Override
        public void run() {
            try {
                Path outputFile = Paths.get(outputPath);

                // Check if file exists
                if (Files.exists(outputFile) && !force) {
                    System.err.println("✗ File already exists: " + outputPath);
                    System.err.println("Use --force to overwrite");
                    System.exit(1);
                    return;
                }

                // Create template
                String template = generateTemplate(title, description);

                // Write to file
                Files.write(outputFile, template.getBytes());

                System.out.println("✓ Created Plans.md: " + outputPath);
                System.out.println("  Title: " + title);
                System.out.println("  Description: " + description);

            } catch (Exception e) {
                System.err.println("✗ Failed to create Plans.md: " + e.getMessage());
                e.printStackTrace();
                System.exit(1);
            }
        }

        private String generateTemplate(String title, String description) {
            return String.format("""
# %s

**目标**: %s

## Phase 1: Initial Setup

### 目标
项目初始化和基础设置

| Task | 内容 | DoD | Depends | Status |
|------|------|-----|---------|--------|
| 1.1 | 项目初始化 | 创建项目结构和基础配置 | 项目构建成功 | - | cc:TODO |
| 1.2 | 配置开发环境 | 设置开发工具和依赖 | 环境测试通过 | 1.1 | cc:TODO |

## Phase 验收标准

### 功能完整性
- [ ] 所有计划任务完成
- [ ] 测试覆盖率达标
- [ ] 文档完整准确

### 质量标准
- [ ] 代码质量符合规范
- [ ] 性能指标达标
- [ ] 安全审查通过

---

## 预估时间

| **阶段** | **时间** | **团队规模** |
|---------|---------|------------|
| Phase 1: Initial Setup | 2 周 | 2 人 |

**总计**: **2 周**

---
*Generated by Java Harness gen command - %s*
""", title, description, LocalDate.now().format(DateTimeFormatter.ISO_DATE));
        }
    }

    /**
     * Check for drift between plan status and actual git state
     */
    @Command(name = "check",
             mixinStandardHelpOptions = true,
             description = "Detect drift between plan status and git commits")
    public static class CheckCommand implements Runnable {

        @Option(names = {"-f", "--file"},
                 description = "Plans.md file to check (default: Plans.md)",
                 defaultValue = "Plans.md")
        private String planFile;

        @Option(names = {"--branch"},
                 description = "Git branch to check against",
                 defaultValue = "master")
        private String branch;

        @Option(names = {"--fix"},
                 description = "Auto-fix detected drift")
        private boolean autoFix;

        @Override
        public void run() {
            try {
                PlanFile plan = new PlanFile(planFile);
                DriftDetector detector = new DriftDetector();

                List<DriftIssue> issues = detector.detectDrift(plan, branch);

                if (issues.isEmpty()) {
                    System.out.println("✓ No drift detected - Plan status matches git state");
                } else {
                    System.out.println("⚠ Drift detected - " + issues.size() + " issue(s) found:");
                    System.out.println();

                    for (DriftIssue issue : issues) {
                        System.out.println("  [" + issue.severity + "] " + issue.taskId);
                        System.out.println("      " + issue.message);
                        if (issue.suggestedFix != null) {
                            System.out.println("      Suggest: " + issue.suggestedFix);
                        }
                        System.out.println();
                    }

                    if (autoFix) {
                        System.out.println("Attempting auto-fix...");
                        int fixed = detector.autoFix(plan, issues);
                        System.out.println("✓ Fixed " + fixed + " issue(s)");
                    }
                }

            } catch (Exception e) {
                System.err.println("✗ Drift check failed: " + e.getMessage());
                e.printStackTrace();
                System.exit(1);
            }
        }
    }

    /**
     * Update plan completion status
     */
    @Command(name = "update",
             mixinStandardHelpOptions = true,
             description = "Update plan completion status")
    public static class UpdateCommand implements Runnable {

        @Option(names = {"-f", "--file"},
                 description = "Plans.md file to update (default: Plans.md)",
                 defaultValue = "Plans.md")
        private String planFile;

        @Option(names = {"--commit"},
                 description = "Update from git commit hash")
        private String commitHash;

        @Option(names = {"--task"},
                 description = "Specific task to update (e.g., 8.2.1)")
        private String taskId;

        @Option(names = {"--status"},
                 description = "New status value",
                 defaultValue = "cc:completed")
        private String status;

        @Override
        public void run() {
            try {
                PlanFile plan = new PlanFile(planFile);

                if (taskId != null) {
                    // Update specific task
                    if (commitHash != null) {
                        status = status + " ✅ " + commitHash;
                    }
                    plan.updateTaskStatus(taskId, status);
                    System.out.println("✓ Updated task " + taskId + " to " + status);
                } else {
                    // Auto-update from git
                    int updated = plan.autoUpdateFromGit();
                    System.out.println("✓ Auto-updated " + updated + " task(s)");
                }

                plan.save();

            } catch (Exception e) {
                System.err.println("✗ Update failed: " + e.getMessage());
                e.printStackTrace();
                System.exit(1);
            }
        }
    }

    /**
     * Validate Plans.md format and structure
     */
    @Command(name = "validate",
             mixinStandardHelpOptions = true,
             description = "Validate Plans.md format and structure")
    public static class ValidateCommand implements Runnable {

        @Option(names = {"-f", "--file"},
                 description = "Plans.md file to validate (default: Plans.md)",
                 defaultValue = "Plans.md")
        private String planFile;

        @Option(names = {"--strict"},
                 description = "Enable strict validation mode")
        private boolean strict;

        @Override
        public void run() {
            try {
                PlanFile plan = new PlanFile(planFile);
                List<ValidationIssue> issues = plan.validate(strict);

                if (issues.isEmpty()) {
                    System.out.println("✓ Plans.md validation passed");
                    System.out.println("  Tasks found: " + plan.getTaskCount());
                    System.out.println("  Structure: Valid");
                } else {
                    System.out.println("✗ Validation failed - " + issues.size() + " issue(s):");
                    System.out.println();

                    for (ValidationIssue issue : issues) {
                        System.out.println("  [" + issue.level + "] " + issue.location);
                        System.out.println("      " + issue.message);
                        System.out.println();
                    }

                    System.exit(1);
                }

            } catch (Exception e) {
                System.err.println("✗ Validation failed: " + e.getMessage());
                e.printStackTrace();
                System.exit(1);
            }
        }
    }

    /**
     * Plan file parser and manager
     */
    public static class PlanFile {
        private final Path filePath;
        private final List<String> lines;
        private final Map<String, TaskInfo> tasks;

        public PlanFile(String filePath) throws IOException {
            this.filePath = Paths.get(filePath);
            this.lines = Files.readAllLines(this.filePath, StandardCharsets.UTF_8);
            this.tasks = new HashMap<>();
            parseTasks();
        }

        private void parseTasks() {
            // Simple pattern to match task rows in markdown tables
            Pattern taskPattern = Pattern.compile("\\|.*?(\\d+\\.\\d+).*?\\|.*?(cc:[^\\|\\s]+).*?\\|");
            Pattern completedPattern = Pattern.compile("cc:completed.*?✅.*?([a-f0-9]+)");

            for (String line : lines) {
                Matcher matcher = taskPattern.matcher(line);
                if (matcher.find()) {
                    String taskId = matcher.group(1);
                    String status = matcher.group(2).trim();

                    TaskInfo info = new TaskInfo();
                    info.taskId = taskId;
                    info.status = status;

                    // Check if completed with commit hash
                    Matcher completedMatcher = completedPattern.matcher(line);
                    if (completedMatcher.find()) {
                        info.commitHash = completedMatcher.group(1);
                    }

                    tasks.put(taskId, info);
                }
            }
        }

        public void updateTaskStatus(String taskId, String newStatus) {
            tasks.put(taskId, new TaskInfo(taskId, newStatus, null));
        }

        public int autoUpdateFromGit() {
            // Simulate auto-update logic
            int updated = 0;
            for (TaskInfo task : tasks.values()) {
                if (task.status.startsWith("cc:TODO") && shouldMarkAsCompleted(task)) {
                    task.status = "cc:completed ✅ auto";
                    updated++;
                }
            }
            return updated;
        }

        private boolean shouldMarkAsCompleted(TaskInfo task) {
            // Logic to determine if task should be marked as completed
            // This would check git commits, file changes, etc.
            return false; // Placeholder
        }

        public List<ValidationIssue> validate(boolean strict) {
            List<ValidationIssue> issues = new ArrayList<>();

            // Check if file is empty
            if (lines.isEmpty()) {
                issues.add(new ValidationIssue("ERROR", "File is empty", "File content"));
                return issues;
            }

            // Check for required sections
            boolean hasTasks = false;
            boolean hasTable = false;

            for (String line : lines) {
                if (line.contains("| Task |")) {
                    hasTable = true;
                }
                if (line.startsWith("| ") && line.contains("| cc:")) {
                    hasTasks = true;
                }
            }

            if (!hasTable) {
                issues.add(new ValidationIssue("ERROR", "Missing task table structure", "Table header"));
            }

            if (!hasTasks) {
                issues.add(new ValidationIssue("WARNING", "No tasks found in plan", "Task entries"));
            }

            if (strict && tasks.size() < 5) {
                issues.add(new ValidationIssue("WARNING", "Plan has fewer than 5 tasks", "Task count"));
            }

            return issues;
        }

        public void save() throws IOException {
            // Save updated content back to file
            Files.write(filePath, lines);
        }

        public int getTaskCount() {
            return tasks.size();
        }

        public Map<String, TaskInfo> getTasks() {
            return tasks;
        }
    }

    /**
     * Drift detection between plan and git state
     */
    public static class DriftDetector {
        public List<DriftIssue> detectDrift(PlanFile plan, String branch) {
            List<DriftIssue> issues = new ArrayList<>();

            for (TaskInfo task : plan.getTasks().values()) {
                if (task.status.equals("cc:completed") && task.commitHash == null) {
                    issues.add(new DriftIssue(
                        "WARNING",
                        task.taskId,
                        "Task marked as completed but missing commit hash",
                        "Add commit hash: cc:completed ✅ <hash>"
                    ));
                }

                if (task.status.equals("cc:completed") && task.commitHash != null) {
                    // Could verify commit exists in git history
                    if (!commitExists(task.commitHash, branch)) {
                        issues.add(new DriftIssue(
                            "ERROR",
                            task.taskId,
                            "Task references non-existent commit hash: " + task.commitHash,
                            "Verify commit hash or update status"
                        ));
                    }
                }
            }

            return issues;
        }

        private boolean commitExists(String commitHash, String branch) {
            try {
                // Check if commit exists in git
                ProcessBuilder pb = new ProcessBuilder("git", "rev-parse", "--verify", commitHash);
                Process process = pb.start();
                return process.waitFor() == 0;
            } catch (Exception e) {
                return false;
            }
        }

        public int autoFix(PlanFile plan, List<DriftIssue> issues) {
            int fixed = 0;

            for (DriftIssue issue : issues) {
                if (issue.severity.equals("WARNING") && issue.suggestedFix != null) {
                    // Apply fix
                    if (issue.suggestedFix.startsWith("Add commit hash")) {
                        // Get current commit
                        String currentCommit = getCurrentCommit();
                        if (currentCommit != null) {
                            TaskInfo task = plan.getTasks().get(issue.taskId);
                            if (task != null) {
                                task.status = "cc:completed ✅ " + currentCommit;
                                task.commitHash = currentCommit;
                                fixed++;
                            }
                        }
                    }
                }
            }

            return fixed;
        }

        private String getCurrentCommit() {
            try {
                ProcessBuilder pb = new ProcessBuilder("git", "rev-parse", "--short", "HEAD");
                Process process = pb.start();
                BufferedReader reader = new BufferedReader(new java.io.InputStreamReader(process.getInputStream()));
                String commit = reader.readLine();
                process.waitFor();
                return commit;
            } catch (Exception e) {
                return null;
            }
        }
    }

    /**
     * Task information holder
     */
    public static class TaskInfo {
        String taskId;
        String status;
        String commitHash;

        public TaskInfo() {}

        public TaskInfo(String taskId, String status, String commitHash) {
            this.taskId = taskId;
            this.status = status;
            this.commitHash = commitHash;
        }
    }

    /**
     * Drift issue holder
     */
    public static class DriftIssue {
        String severity;
        String taskId;
        String message;
        String suggestedFix;

        public DriftIssue(String severity, String taskId, String message, String suggestedFix) {
            this.severity = severity;
            this.taskId = taskId;
            this.message = message;
            this.suggestedFix = suggestedFix;
        }
    }

    /**
     * Validation issue holder
     */
    public static class ValidationIssue {
        String level;
        String location;
        String message;

        public ValidationIssue(String level, String location, String message) {
            this.level = level;
            this.location = location;
            this.message = message;
        }
    }

    /**
     * Main entry point for testing
     */
    public static void main(String[] args) {
        int exitCode = new CommandLine(new GenCommand()).execute(args);
        System.exit(exitCode);
    }
}